server:
  port: 8080
spring:
  application:
    name: customer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
    password: p4ssword
    url: jdbc:mysql://localhost:3306/microservice_customers

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect